use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'LZToastHelper_Example' do
  pod 'LZToastHelper', :path => '../'

  target 'LZToastHelper_Tests' do
    inherit! :search_paths

  end
end
